version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
    reviewers:
      - lptn
    assignees:
      - ixdf-bot

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
    reviewers:
      - hasan-wajahat
    assignees:
      - ixdf-bot
