blank_issues_enabled: false
contact_links:
  - name: Support Questions & Other
    url: https://github.com/InteractionDesignFoundation/nova-unlayer-field/discussions
    about: 'If you have a question or need help using the library, click:'
